version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ppiitprojectdb
    ports:
      - "3306:3306"
    volumes:
      - ./backend/ppiitprojectdb.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  php:
    image: php:8.1-apache
    volumes:
      - ./backend:/var/www/html
      - ./apache.conf:/etc/apache2/conf-available/cors.conf
    ports:
      - "8000:80"
    command: >
      bash -c "a2enmod headers &&
              a2enconf cors &&
              docker-php-ext-install mysqli &&
              apache2-foreground"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
