services:
  # MySQL database service - Stores application data in a relational database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ppiitprojectdb
    ports:
      - "3306:3306"  # Expose MySQL port to host
    volumes:
      - ./backend/ppiitprojectdb.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize database with schema
    command: >
      --default-authentication-plugin=mysql_native_password
    restart: always  # Container will always restart unless stopped manually
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PHP with Apache web server service - Hosts the backend PHP application
  php:
    image: php:8.1-apache
    volumes:
      - ./backend:/var/www/html  # Mount backend code to web server root
      - ./apache.conf:/etc/apache2/conf-available/cors.conf  # Configure CORS
    ports:
      - "8000:80"  # Map container port 80 to host port 8000
    command: >
      bash -c "a2enmod headers &&
              a2enconf cors &&
              docker-php-ext-install mysqli &&
              apache2-foreground"  # Enable required Apache modules and PHP extensions
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    depends_on:
      - mysql  # Wait for MySQL to start before launching PHP service

  # phpMyAdmin for database management - Web interface to manage MySQL database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql  # Connect to MySQL container
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"  # Access phpMyAdmin at localhost:8080
    depends_on:
      - mysql
